---

variables:
  - MOLECULE_INSTANCE_NAME: $CI_JOB_ID

default:
  before_script:
    - |
      sudo apt-get update
      sudo apt-get -y install bridge-utils dnsmasq-base ebtables libguestfs-tools libvirt-clients libvirt-daemon-system libvirt-dev qemu-kvm qemu-utils ruby-dev

    - |
      curl -Os https://releases.hashicorp.com/vagrant/2.2.14/vagrant_2.2.14_x86_64.deb
      curl -Os https://releases.hashicorp.com/vagrant/2.2.14/vagrant_2.2.14_SHA256SUMS
      curl -Os https://releases.hashicorp.com/vagrant/2.2.14/vagrant_2.2.14_SHA256SUMS.sig
      curl -skL https://keybase.io/hashicorp/pgp_keys.asc | sudo gpg --import
      sudo gpg --verify vagrant_2.2.14_SHA256SUMS.sig vagrant_2.2.14_SHA256SUMS
      sha256sum -c vagrant_2.2.14_SHA256SUMS 2>&1 | grep OK
      sudo dpkg -i vagrant_2.2.14_x86_64.deb
      sudo vagrant plugin install vagrant-libvirt
      rm -rf vagrant_2.2.14_*

    - |
      sudo apt-get update
      sudo apt-get -y install ca-certificates curl gcc iproute2 pwgen python3 python3-dev sudo
      curl -skL https://bootstrap.pypa.io/get-pip.py | sudo -H python3 - --prefix=/usr/local
      sudo -H pip3 install --prefix=/usr/local --upgrade --ignore-installed --requirement requirements.txt

    - |
      export ROLE=$(echo $CI_PROJECT_NAME | sed 's/^.*\/ansible-role-/\//g')
      mkdir -p $HOME/.ansible/roles
      mkdir -p $HOME/.ansible/collections/alvistack
      ln -s $CI_PROJECT_DIR $HOME/.ansible/roles/$ROLE

job:
  ubuntu-20.04:
    script:
      - sudo -E molecule test -s ubuntu-20.04

  ubuntu-18.04:
    script:
      - sudo -E molecule test -s ubuntu-18.04

  ubuntu-20.10:
    script:
      - sudo -E molecule test -s ubuntu-20.10
    allow_failure: true

  centos-8:
    script:
      - sudo -E molecule test -s centos-8
    allow_failure: true

  centos-7:
    script:
      - sudo -E molecule test -s centos-7
    allow_failure: true

  suse-15:
    script:
      - sudo -E molecule test -s suse-15
    allow_failure: true

  debian-10:
    script:
      - sudo -E molecule test -s debian-10
    allow_failure: true

  fedora-33:
    script:
      - sudo -E molecule test -s fedora-33
    allow_failure: true
